# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive

      # Runs a set of commands using the runners shell
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[16.10,16.11)'
          
          
      - name: Install Composer Dependencies
        working-directory: ./models
        run: git lfs pull --include="vision/classification/squeezenet/model/squeezenet1.1-7.onnx" --exclude=""
        
      - name: copy file
        run: cp "./models/vision/classification/squeezenet/model/squeezenet1.1-7.onnx" "./ProjectBangalore/Assets"
        
      - name: rename model file
        run: ren "./ProjectBangalore/Assets/squeezenet1.1-7.onnx" "model.onnx"

      - name: MSBuild
        working-directory: ./ProjectBangalore
        run: msbuild ProjectBangalore.csproj /restore
        
        
        
        
